env:
  browser: true
  es2021: true
extends:
  - "@nuxtjs"
  - "@nuxtjs/eslint-config-typescript"
overrides: []
parserOptions:
  # parser: "@babel/eslint-parser"
  requireConfigFile: false
  ecmaVersion: latest
  sourceType: module
rules: {}
