name: Scheduled build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python # Pythonのセットアップ
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.3" # Pythonのバージョン指定

      - name: Install dependencies # 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py # PythonでSalmon Statsからデータ取得
        run: |
          python main.py

      - name: Commit and Push # 実行結果をプッシュしてレポジトリに反映
        run: |
          git config --local user.email "nasawake.am@gmail.com"
          git config --local user.name "tkgstrator"
          git add .
          git commit -m "Update product information"
          git config pull.rebase false
          git pull
          git push origin master
